Feat/#109/user find one
modern-agile-team/dongurami-server-v2 pull request #111
Opened 2024-01-02 03:49 UTC by hobiJeong

### Description
유저 정보 찾기 api 입니다.

### To Reviewer
일단은 둘 다 토큰에서 가져온 id로 조회하도록 만들었습니다.

### Reference Link

### Related Issue Link
#109 

### API

| Method | Path      | 설명           | 작업(추가, 수정, 삭제) |
| ------ | --------- | -------------- | ---------------------- |
| GET    | /api/users/profile | 유저 정보 조회(id) | 추가                   |
| GET    | /api/users | 유저 정보 조회(where) | 추가                   |

2024-01-02 07:28 UTC, rrgks6221 commented
@hobiJeong 아직 codeowners 에 창훈이형이 없는데 그 전에는 리뷰어로 수동으로라도 추가해주세요

2024-01-02 08:01 UTC, hobiJeong commented
> @hobiJeong 아직 codeowners 에 창훈이형이 없는데 그 전에는 리뷰어로 수동으로라도 추가해주세요

넵!

2024-01-02 11:45 UTC, rrgks6221 commented on src/apis/users/controllers/users.controller.ts
> +  @ApiUsers.FindOneBy({ summary: '유저 찾기 (여러 조건)' })
여러조건이라는건 service 레이어에서 여러 조건으로 find 하게 만든걸 말하는거같은데 클라이언트측과는 관계없기때문에 올바르지 않은거같네요

2024-01-02 11:46 UTC, rrgks6221 commented on src/apis/users/controllers/users.controller.ts
> +  findOneBy(@User() user: UserDto) {
지금 path 가 /api/users 인데 이렇게 되면 유저 리스트를 조회하는걸 예상하게 됩니다.
rest api 에 대해 리서치해보고 변경되면 좋을듯합니다.
추가로 제가 기존에 존재하는 service method 를 사용하면 된다고 했었는데 상세조회에 경우에는 리소스가 존재하지 않는 경우가 처리돼야해서 method를 새로 하나 만들어야겠네요.

2024-01-02 14:05 UTC, hobiJeong commented on src/apis/users/controllers/users.controller.ts
> +  findOneBy(@User() user: UserDto) {
> 지금 path 가 /api/users 인데 이렇게 되면 유저 리스트를 조회하는걸 예상하게 됩니다. rest api 에 대해 리서치해보고 변경되면 좋을듯합니다. 추가로 제가 기존에 존재하는 service method 를 사용하면 된다고 했었는데 상세조회에 경우에는 리소스가 존재하지 않는 경우가 처리돼야해서 method를 새로 하나 만들어야겠네요.

일단은 보안 혹은 추후에 본인 정보 열람인지 여부를 위해 가드도 설정은 해놨는데 필요 없을 것 같으면 빼겠습니다!

2024-01-02 14:25 UTC, rrgks6221 requested changes

2024-01-02 14:25 UTC, rrgks6221 commented on src/apis/users/controllers/users.controller.ts
> +  @Get(':userId/profile')
profile 이라는 path 는 들어가지 않아도 될듯합니다.
user 조회가 아닌 user 에서 관리하는 profile 이라는 리소스가 있는데 이걸 조회하는듯한 느낌이 있어요
auth 쪽에 profile 이 들어가는 이유는 auth(인증) 이라는 path 에 로그인한 사용자의 profile 정보라는 의미로 들어가는 경우입니다.

2024-01-02 14:25 UTC, rrgks6221 commented on src/apis/users/controllers/users.controller.ts
> +  @UseGuards(JwtAuthGuard)
코멘트에 달아주신 거처럼 단순히 유저를 조회하는 경우에 인증된 사용자만 사용할 수 있다는 제약을 걸 필요는 없을거같아요

2024-01-02 14:25 UTC, rrgks6221 commented on src/apis/users/controllers/users.controller.ts
> +    @Param() userId: number,
지금 route parameter 로 들어오는 userId 가 number 라는 보장이 없네요.
path 를 통해 들어오니 실제 들어오는 값의 타입은 string 으로 예상됩니다.

2024-01-02 14:25 UTC, rrgks6221 commented on src/apis/users/controllers/users.controller.ts
> +  findOneBy(@User() user: UserDto) {
네 우선은 빼는쪽으로 작업 부탁드립니다.

2024-01-03 01:04 UTC, rrgks6221 approved these changes
커밋 히스토리를 봤을 때 사용하지 임포트를 제거한거같은데 아주 좋은 습관입니다.
수동으로 확인했을 때 제거하는 방법은 신경써야하는 부분이 많을거로 예상되는데 vscode 설정에 저장시 액션 중 사용하지 않는 import 제거 옵션 등 다양한 방법이 있으니 최적화하는거도 많은 도움이 될거같아요.

2024-01-03 02:58 UTC, ohchanghoon approved these changes
보면서 배울게요 ~

2024-01-03 02:59 UTC, merged