Feat/#66/notice board crud remove
modern-agile-team/dongurami-server-v2 pull request #99
Opened 2023-12-08 05:58 UTC by hobiJeong

### Description
remove 기능 만들어 봤습니다

### To Reviewer
마찬가지로 석호님 코드를 참고 안하고 혼자 만들어 본거라 많이 이상할 것 같습니다 ㅠㅠ

### Reference Link

### Related Issue Link
#66 

### API

| Method | Path      | 설명           | 작업(추가, 수정, 삭제) |
| ------ | --------- | -------------- | ---------------------- |
| Delete    | /api/notice-posts | 공지 게시글 삭제 | 추가                   |

2023-12-08 07:40 UTC, rrgks6221 commented
@hobiJeong draft 후에 #98 반영사항을 해당 PR 에 없을 떄 다시 ready review 를 해주세요

2023-12-09 07:30 UTC, rrgks6221 commented
이전 pr 내용 없애주세요

2023-12-09 08:00 UTC, hobiJeong reviewed
@rrgks6221 이전 pr내용 없앴습니다!

아 지금 수정할 것만 수정하고 다시 언급 드릴게요!

2023-12-09 08:06 UTC, hobiJeong commented
> 이전 pr 내용 없애주세요

@rrgks6221 
리뷰해주시면 될 것 같습니다!

2023-12-09 09:07 UTC, rrgks6221 requested changes

2023-12-09 09:07 UTC, rrgks6221 commented on src/apis/notice-posts/services/notice-posts.service.ts
> +      const removedPost = await this.findOneOrNotFound(noticePostId);
삭제한다는건 데이터가 바뀌지 않는다는거니까 위에서 조회한 post 를 가지고 history 를 쌓아도 무방할거같아요

2023-12-09 09:07 UTC, rrgks6221 commented on src/apis/notice-posts/services/notice-posts.service.ts
> +    try {
patch update 에서 제대로 확인을 못했는데 commit 이 두번 들어가있네요. 트렌젝션에 대해 한번 알아보고 적절하게 트렌젝션을 핸들링하면 좋을거같습니다.

2023-12-09 09:07 UTC, rrgks6221 commented on src/apis/notice-posts/controllers/notice-posts.controller.ts
> +  remove(
이거 성공시에 에러나지 않나요???

2023-12-09 15:50 UTC, hobiJeong commented on src/apis/notice-posts/controllers/notice-posts.controller.ts
> +  remove(
네 실행은 잘되는데 return할 때 type이 delete가 들어가서 인터셉터에서 number타입이 아니라 에러를 뱉네요.

2023-12-09 15:50 UTC, hobiJeong commented on src/apis/notice-posts/services/notice-posts.service.ts
> +    try {
제가 좀 잘못 이해하고 있었네요! 커밋이 된 후에 find를 통해 post를 찾아야 업데이트 된 데이터를 history에 저장할 수 있다고 생각 했는데 완전히 잘못 생각했네요.. patch 메서드 부분까지 commitTransaction 수정했습니다!

2023-12-09 15:50 UTC, hobiJeong commented on src/apis/notice-posts/services/notice-posts.service.ts
> +      const removedPost = await this.findOneOrNotFound(noticePostId);
근데 history에는 status가 posting인 상태로 올라가는데 괜찮을까요?

2023-12-10 08:17 UTC, rrgks6221 commented on src/apis/notice-posts/services/notice-posts.service.ts
> +      const removedPost = await this.findOneOrNotFound(noticePostId);
어처피 변경되는건 status 뿐이니 history method 에 값을 넘겨줄 때 status 만 변경해서 넘겨주는게 퍼포먼스적으로도 좋을거같아요.

2023-12-10 08:17 UTC, rrgks6221 commented on src/apis/notice-posts/controllers/notice-posts.controller.ts
> +  remove(
실행 잘 되게 변경해주세요

2023-12-10 08:48 UTC, rrgks6221 reviewed
구두로 얘기한 내용 반영해주세요

2023-12-10 09:25 UTC, rrgks6221 commented on src/apis/notice-posts/services/notice-posts.service.ts
> +      return 1;
메서드에서 반환해주는 값을 사용해주는게 더 적절할듯 합니다.

2023-12-10 11:15 UTC, rrgks6221 approved these changes

2023-12-10 11:15 UTC, merged